version: '3.8'

services:
  phpfpm:
    image: php:8.3-fpm
    container_name: phpfpm
    build: docker/php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached # Monte le répertoire local dans le conteneur
      - .docker/php/php.ini:/usr/local/etc/php/php.ini # Optionnel : fichier de configuration PHP personnalisé
    depends_on:
      - mongodb
      - mysql
    networks:
      - app-network

  mongodb:
    image: mongo:latest # Utilise la dernière version de MongoDB
    container_name: mongodb
    ports:
      - "27017:27017" # Expose le port MongoDB par défaut
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db # Monte un volume pour les données persistantes
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./public:/var/www/html:ro,cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf # Utilisez un fichier de configuration nginx personnalisé
    ports:
      - "8080:80"
    depends_on:
      - phpfpm
    networks:
      - app-network

  graphql:
    build:
      context: ./docker/graphql
    container_name: graphql
    ports:
      - "4000:4000"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  mongodb_data:
    driver: local
  mysql_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
    driver: local

networks:
  app-network:
    driver: bridge
