elasticsearch:
  hosts: ['http://elasticsearch:9200'] # URL de votre instance Elasticsearch
  username: 'elastic'             # Remplacez par l'utilisateur configuré (facultatif)
  password: 'test'

# ---------------------------------- Network -----------------------------------
network.host: 0.0.0.0

# ---------------------------------- Cluster -----------------------------------
cluster.name: "docker-cluster"

# The node name can be used to differentiate nodes in a multi-node cluster
node.name: "node-1"

# Elasticsearch will use the "single-node" discovery type in a non-clustered configuration
discovery.type: single-node

# ---------------------------------- Security -----------------------------------
# Désactive la sécurité pour un environnement de développement. Pour un usage en production, il est recommandé de configurer la sécurité.
xpack.security.enabled: true

# ---------------------------------- Memory ------------------------------------
# Paramètres liés à la mémoire (facultatif, mais utile pour des machines locales)
# (Modification du Java heap size)
ES_JAVA_OPTS: "-Xms1g -Xmx1g"

# ---------------------------------- Logging -----------------------------------
# Définir le niveau de log
logger.level: info

# ---------------------------------- Index -------------------------------------
# Configurations de base pour les index (ceci est souvent utilisé pour des règles de taille des index)
index.number_of_shards: 1
index.number_of_replicas: 0
